version: '3.9'

services:
  backend:
    container_name: plataforma-mentoria-backend
    build:
      context: ./backend/plataforma.mentoria
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - app-network
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}

  frontend:
    container_name: plataforma-mentoria-frontend
    build:
      context: ./frontend
    ports:
      - "3000:80"
    restart: on-failure
    networks:
      - app-network
    depends_on:
      - backend

  database:
    container_name: plataforma-mentoria-database
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: